### ISSUE TITLE
WIFI stop after some time

### ISSUE THREAD

**Issue by oopen** [db260179/openwrt-bpi-r1#2]
Hello, good version! 
I have configured wifi to use WPA2 with forced AES and 40 MHz width.
All work but after some time like 5 or 10 minutes it does not respond.
Computers still connected to the AP, but no respond even ping on IP lan interface.
If I disable en re-enable wifi on my computers it work, but after some time not..
But all RJ45 lan ports work

**Comment by db260179** [comment]
I'm afraid this is a known issue with this board. Have you tried my prebuilt release?

**Comment by bloedersack** [comment]
Hello,

i have problems with wifi too. i use access point with wpa2-psk and force ccmp (aes). my wifi devices get a connection and after some secondes they disconnect. The devices get a reconnect after some seconds again... i get almost a stable connection in legacy mode. I cant find a wifi log to check if is a device or router problem. Can you help me here plz.

A reproducible issus is with auto channel. The access point are not "created" and i get the message: "Wireless is disabled or not associated".

Thanks a lot for your running os and shame to banana pi for their broken images...

**Comment by db260179** [comment]
Is this using my github sources or my prebuilt image?

if this is with another image not made by me, please don't added issues that are not related to this source tree.
Thanks

**Comment by bloedersack** [comment]
I use your [Chaos Calmer - v1.0 Stable release](http://www.bananapi.com/index.php/forum/openwrt/1951-chaos-calmer-v1-0-stable-release-for-bpi-r1-github-sources-as-well) image. I searched the link for this post and see there is a version 1.1. I dont know which version i actual using. 

I will check it later.

**Comment by bloedersack** [comment]
Ok, im using an older version. I am sorry. Please ignore my issus. I will update my os and check it again. If i have still problems then i will open a new post.

Thanks.
